version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    expose:
      - "5432"
    env_file:
      - ./etl_service/.env
    volumes:
      - /postgresql/data:/var/lib/postgresql/data
      - ./postgres_dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
      
  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    volumes:
      - ./etl_service/entrypoint.sh:/entrypoint.sh
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  etl_service:
    build: etl_service
    container_name: etl_service
    env_file:
      - ./etl_service/.env
    depends_on:
      - elasticsearch
      - postgres
    command: python main.py

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - elasticsearch
